api_login_check:
    path: /api/login_check

users:
    type: rest
    resource: "@AppBundle/Controller/UsersController.php"
    prefix: /api

notices:
    type: rest
    resource: "@AppBundle/Controller/NoticeController.php"
    prefix: /api

categories:
    type: rest
    resource: "@AppBundle/Controller/CategoryController.php"
    prefix: /api

images:
    resource: "@AppBundle/Controller/ImageController.php"
    prefix: /images
    type:  annotation
