api_login_check:
    path: /api/login_check

main:
    type: annotation
    resource: "@AppBundle/Controller/DefaultController.php"
    prefix: /

users:
    type: rest
    resource: "@AppBundle/Controller/UsersController.php"
    prefix: /api

ads:
    type: rest
    resource: "@AppBundle/Controller/AdController.php"
    prefix: /api

categories:
    type: rest
    resource: "@AppBundle/Controller/CategoryController.php"
    prefix: /api
