<?php

namespace AppBundle\Repository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParams(array $params)
    {
        if(empty($params['category'])) {
            return $this->findAll();
        }
        
        return $this->findBy([
            'category' => $params['category']
        ]);

    }
}
