<?php

namespace AppBundle\Repository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParams(array $params)
    {
        $params = array_filter($params, function ($value) {
            return !empty($value);
        });

        return $this->findBy($params);
    }
}
