<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * Notice repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParams(array $params)
    {
        $params = array_filter($params, function ($value) {
            return !empty($value);
        });
        $query = $this->createQueryBuilder('noticeRepository')
            ->select('n')
            ->from('AppBundle:Notice', 'n');

        if (!empty($params['username'])) {
            $user = $this->getEntityManager()
                ->getRepository('AppBundle:User')
                ->findOneBy(['username' => $params['username']]);

            if (!empty($user)) {
                $params['user'] = $user->getId();
                unset($params['username']);
            }

        }

        foreach ($params as $key => $value) {
            $query->andWhere(sprintf('n.%s=:%s', $key, $key));
            $query->setParameter($key, $value);
        }

        return $query->getQuery()->getResult();
    }
}
