<?php

namespace AppBundle\Repository;

/**
 * Notice repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParams(array $params)
    {
        $params = array_filter($params, function ($value) {
            return !empty($value);
        });

        $query = $this->createQueryBuilder('n')
            ->select('user', 'category', 'notice')
            ->from('AppBundle:Notice', 'notice')
            ->join('notice.category', 'category')
        ;

        if(!empty($params['username'])) {
            $query->join('notice.user', 'user')
                ->where('user.username=:username')
                ->setParameter('username', $params['username']);

            unset($params['username']);
        }

        foreach ($params as $key => $value) {
            $query->andWhere(sprintf('notice.%s=:%s', $key, $key ));
            $query->setParameter($key, $value);
        }

        return $query->getQuery()->getResult();
    }
}
