<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * Notice repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeRepository extends \Doctrine\ORM\EntityRepository
{
    private $resultsPerPage = 6;

    public function findByParams(array $params)
    {
        $params = array_filter($params, function ($value) {
            return !empty($value);
        });

        $query = $this->createQueryBuilder('n')
            ->orderBy('n.id', 'DESC')
            ->setMaxResults($this->resultsPerPage)
        ;

        if (!empty($params['username'])) {
            $user = $this->getEntityManager()
                ->getRepository('AppBundle:User')
                ->findOneBy(['username' => $params['username']]);

            if (!empty($user)) {
                $params['user'] = $user->getId();
                unset($params['username']);
            }
        }

        if(isset($params['page'])) {
            $query->setFirstResult($params['page'] * $this->resultsPerPage);
            unset($params['page']);
        }

        foreach ($params as $key => $value) {
            $query->where(sprintf('n.%s=:%s', $key, $key));
            $query->setParameter($key, $value);
        }

        return $query->getQuery()->getResult();
    }
}
